Сдача на проверку практического задания спринта 9
MishanyaCh/java-filmorate pull request #5
Opened 2023-09-12 23:06 UTC by MishanyaCh

2023-09-17 06:44 UTC, YazykovMikhail commented
Написал комментарии многие из них актуальны для двух контролеров/моделей film и user, когда поправляешь в одном месте, сразу посомтри как у тебя во всех других таких же местах.

2023-09-17 06:45 UTC, YazykovMikhail requested changes

2023-09-17 06:45 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Map<Integer, Film> films = new HashMap<>();
не надо делать статичным это поле конкретного инстаса(обьекта), в каждом обьекте этого класса должен быть свой список

2023-09-17 06:45 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
рекоменду использовать над полями аннотации
	@NotBlank
	@Size(min = 1, max = 200)
	@NotNull
	
и так далее
что бы валидация проходила автоматически

2023-09-17 06:45 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final String name;
лучше неделать поля в модели/dto финальными, они имеют свойство изменяться

2023-09-17 06:45 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final String email;
лучше неделать поля в модели/dto финальными, они имеют свойство изменяться

2023-09-17 06:45 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
рекоменду использовать над полями аннотации
@notblank
@SiZe(min = 1, max = 200)
@NotNull

и так далее
что бы валидация проходила автоматически

2023-09-17 06:45 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User createUser(@RequestBody User user) {
так же что бы валидация через анноатции работала, нужно будет тут поставить

public User createUser(@Validated @RequestBody User user) {

и везде в контроллере где нужна валидация через аннотации

2023-09-17 06:45 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final FilmValidation validator = new FilmValidation();
лучше методы в классе FilmValidation сделай статичными, тогда это поле вообще не нужно будет
Тогда методы можно будет вызывать
FilmValidation.validate напрямую без инстаса

2023-09-17 06:45 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmValidation.java
> +    public void validate(Film film) {
оставь тут только ту валидацию, котору нельзя сделать через аннотации

2023-09-17 06:45 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/validation/UserValidation.java
> +    public void validate(User user) {
оставь тут только ту валидацию, котору нельзя сделать через аннотации

2023-09-17 06:45 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
Стандартынй шаблон для логов
createMethod(Request request) {
log.info("пришел Post запрос /films с телом: {}", request)
Response response = //логика метода, если есть бизнес процессы для логирвоания логируем их
log.info("Отправлен ответ Post /films с телом: {}", response)
}
что бы было видно что пришло, что ушло и если были какие то изменения в процессы выполнянения тоже были видны, потому что ты пойдешь в логи когда у тебя что то сломалось, просто по сообщения "Фильм добалвен" ничего не понятно.

2023-09-17 06:45 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.debug("Количество фильмов в базе: {}", films.size());
ты берешь размер у списка которые хранится в "базе", но за это врмя туда может попасть новое занчение и и когда ты вернешь спсиок он будет уже другой.

	@GetMapping("/films")
	public List<Film> getAll() {
	       log.debug("Пришел GET /films запрос);
		final List<Film> films = new ArrayList<>(films.values());
		log.info("Отправлен ответ GET /films с размером тела:", films.size());
		return films;
	}

2023-09-18 17:22 UTC, MishanyaCh commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final String name;
поправил

2023-09-18 17:23 UTC, MishanyaCh commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final String email;
поправил

2023-09-18 17:24 UTC, MishanyaCh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Map<Integer, Film> films = new HashMap<>();
поправил

2023-09-18 17:33 UTC, MishanyaCh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final FilmValidation validator = new FilmValidation();
поправил

2023-09-18 18:46 UTC, MishanyaCh commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
поправил

2023-09-18 18:46 UTC, MishanyaCh commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
поправил

2023-09-19 07:52 UTC, MishanyaCh commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User createUser(@RequestBody User user) {
поправил

2023-09-19 07:52 UTC, MishanyaCh commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmValidation.java
> +    public void validate(Film film) {
поправил

2023-09-19 07:52 UTC, MishanyaCh commented on src/main/java/ru/yandex/practicum/filmorate/validation/UserValidation.java
> +    public void validate(User user) {
поправил

2023-09-19 08:13 UTC, MishanyaCh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.debug("Количество фильмов в базе: {}", films.size());
поправил

2023-09-19 21:46 UTC, MishanyaCh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
поправил

2023-09-29 01:33 UTC, merged